function createDashboardPage({ supportEmail }, { layout, navigation, escapeHtml }) {
  function script() {
    return String.raw`
const ids=['productName','category','channel','sourceUrl','sourceCost','inboundShipping','packaging','fixedFee','salePrice','marketplaceFeePct','paymentFeePct','adReservePct','returnReservePct','targetMarginPct','demandScore','competitionScore','supplierConfidence','evidenceCount'];let current=null;
const euro=n=>n===null||!Number.isFinite(Number(n))?'—':new Intl.NumberFormat('en-BE',{style:'currency',currency:'EUR'}).format(Number(n));const pct=n=>Number(n).toFixed(1)+'%';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inputData(){const d={};ids.forEach(id=>{const el=document.getElementById(id);d[id]=el.type==='number'||el.type==='range'?Number(el.value):el.value});return d}
function syncPair(base){const range=document.getElementById(base),num=document.getElementById(base+'Num'),out=document.getElementById(base+'Out');const set=v=>{v=Math.max(0,Math.min(100,Number(v)||0));range.value=v;num.value=v;out.textContent=v;update()};range.addEventListener('input',()=>set(range.value));num.addEventListener('input',()=>set(num.value))}['demandScore','competitionScore','supplierConfidence'].forEach(syncPair);
async function update(){try{const res=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(inputData())});if(!res.ok)throw new Error('Calculation failed');current=await res.json();render()}catch(err){document.getElementById('verdictCopy').textContent=err.message}}
function render(){const p=current,m=p.metrics,v=p.verdict.toLowerCase(),decision=document.getElementById('decision');decision.className='decision '+v;document.getElementById('verdict').textContent=p.verdict;document.getElementById('verdictCopy').textContent=p.verdict==='GO'?'The current assumptions clear the economic and downside gates. Validate with a small real-world test before scaling.':p.verdict==='VALIDATE'?'The base case may work, but one or more assumptions still need stronger proof or downside protection.':'Do not commit inventory under the current assumptions. Change the economics or collect materially stronger evidence.';document.getElementById('score').textContent=m.opportunityScore+' / 100';document.getElementById('scoreFill').style.width=m.opportunityScore+'%';document.getElementById('profit').textContent=euro(m.profit);document.getElementById('margin').textContent=pct(m.marginPct);document.getElementById('roi').textContent=pct(m.roiPct);document.getElementById('breakEven').textContent=euro(m.breakEvenPrice);document.getElementById('maxLanded').textContent=euro(m.maxLandedCostAtTargetMargin);document.getElementById('maxSource').textContent=euro(m.maxSourceCostAtTargetMargin);const labels={base:'Base case',sourceCostPlus15:'Source cost +15%',salePriceMinus10:'Selling price −10%',returnsPlus5:'Returns +5 points',combinedDownside:'Combined downside'};document.getElementById('scenarios').innerHTML=Object.entries(p.scenarios).map(([key,s])=>'<tr><td>'+labels[key]+'</td><td>'+euro(s.profit)+'</td><td>'+pct(s.marginPct)+'</td><td><span class="tag '+(s.profit>=0?'go':'no-buy')+'">'+(s.profit>=0?'PROFIT':'LOSS')+'</span></td></tr>').join('');document.getElementById('reasons').innerHTML=p.reasons.map(x=>'<li>'+esc(x)+'</li>').join('');document.getElementById('risks').innerHTML=p.risks.map(x=>'<li>'+esc(x)+'</li>').join('');document.getElementById('plan').innerHTML=p.validationPlan.map(x=>'<li>'+esc(x)+'</li>').join('')}
ids.filter(id=>!['demandScore','competitionScore','supplierConfidence'].includes(id)).forEach(id=>document.getElementById(id).addEventListener('input',update));function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}function slug(s){return String(s||'product').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'product'}
document.getElementById('downloadJson').addEventListener('click',()=>current&&download('demandmine-'+slug(current.product.name)+'.json',JSON.stringify(current,null,2),'application/json'));document.getElementById('downloadCsv').addEventListener('click',()=>{if(!current)return;const rows=[['field','value'],['passport_id',current.passportId],['generated_at',current.generatedAt],['product',current.product.name],['category',current.product.category],['channel',current.product.channel],['verdict',current.verdict],['opportunity_score',current.metrics.opportunityScore],['landed_cost_eur',current.metrics.landedCost],['profit_eur',current.metrics.profit],['margin_pct',current.metrics.marginPct],['roi_pct',current.metrics.roiPct],['break_even_price_eur',current.metrics.breakEvenPrice],['max_landed_cost_eur',current.metrics.maxLandedCostAtTargetMargin],['max_source_cost_eur',current.metrics.maxSourceCostAtTargetMargin],['combined_downside_profit_eur',current.scenarios.combinedDownside.profit],['risks',current.risks.join(' | ')],['validation_plan',current.validationPlan.join(' | ')]];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');download('demandmine-'+slug(current.product.name)+'.csv',csv,'text/csv;charset=utf-8')});document.getElementById('printPassport').addEventListener('click',()=>window.print());
function getSaved(){try{return JSON.parse(localStorage.getItem('demandmine_passports')||'[]')}catch{return[]}}function renderSaved(){const items=getSaved(),target=document.getElementById('saved');target.innerHTML=items.length?items.map((p,i)=>'<div class="saveditem"><div><b>'+esc(p.product.name)+'</b><span class="tag '+p.verdict.toLowerCase()+'">'+p.verdict+'</span><small>'+new Date(p.generatedAt).toLocaleString()+' · score '+p.metrics.opportunityScore+'</small></div><button class="btn smallbtn danger" data-delete="'+i+'">Delete</button></div>').join(''):'<p class="muted">No saved passports yet.</p>';target.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>{const arr=getSaved();arr.splice(Number(btn.dataset.delete),1);localStorage.setItem('demandmine_passports',JSON.stringify(arr));renderSaved()}))}document.getElementById('savePassport').addEventListener('click',()=>{if(!current)return;const arr=getSaved();arr.unshift(current);localStorage.setItem('demandmine_passports',JSON.stringify(arr.slice(0,100)));document.getElementById('saveNotice').textContent='Saved locally at '+new Date().toLocaleTimeString()+'.';renderSaved()});renderSaved();update();
`;
  }

  function dashboard() {
    return layout('DemandMine Decision Workspace', 'Build and export a Product Decision Passport.', `<div class="wrap app">${navigation(true)}<header class="apphead"><div><div class="eyebrow">Paid founding workspace</div><h1>Build a Product Decision Passport</h1><p class="muted">Change any assumption. The verdict and every export update instantly.</p></div><span class="pill">Saved locally in this browser</span></header><div class="appgrid"><section class="card formcard"><div class="eyebrow">Product assumptions</div><h2>Inputs</h2><div class="formgrid">
      <div class="field full"><label for="productName">Product idea</label><input id="productName" maxlength="120" value="Leather alphabet stamp set"></div><div class="field"><label for="category">Category</label><input id="category" maxlength="80" value="Craft tool"></div><div class="field"><label for="channel">Sales channel</label><select id="channel"><option>Etsy</option><option>eBay</option><option>Amazon</option><option>Shopify</option><option>Local retail</option><option>Wholesale</option><option>Marketplace</option><option>Other</option></select></div><div class="field full"><label for="sourceUrl">Supplier/source URL (optional)</label><input id="sourceUrl" type="url" maxlength="500" placeholder="https://..."></div>
      <div class="field"><label for="sourceCost">Source unit cost (€)</label><input id="sourceCost" type="number" min="0" step="0.01" value="13.20"></div><div class="field"><label for="inboundShipping">Inbound/direct shipping (€)</label><input id="inboundShipping" type="number" min="0" step="0.01" value="2.80"></div><div class="field"><label for="packaging">Packaging/handling (€)</label><input id="packaging" type="number" min="0" step="0.01" value="1.00"></div><div class="field"><label for="fixedFee">Fixed transaction fee (€)</label><input id="fixedFee" type="number" min="0" step="0.01" value="0.30"></div><div class="field"><label for="salePrice">Expected selling price (€)</label><input id="salePrice" type="number" min="0" step="0.01" value="32.95"></div><div class="field"><label for="targetMarginPct">Target net margin (%)</label><input id="targetMarginPct" type="number" min="0" max="90" step="0.5" value="25"></div>
      <div class="field"><label for="marketplaceFeePct">Marketplace fee (%)</label><input id="marketplaceFeePct" type="number" min="0" max="80" step="0.1" value="9.5"></div><div class="field"><label for="paymentFeePct">Payment fee (%)</label><input id="paymentFeePct" type="number" min="0" max="30" step="0.1" value="3"></div><div class="field"><label for="adReservePct">Advertising reserve (%)</label><input id="adReservePct" type="number" min="0" max="80" step="0.5" value="5"></div><div class="field"><label for="returnReservePct">Returns/issues reserve (%)</label><input id="returnReservePct" type="number" min="0" max="80" step="0.5" value="4"></div>
      <div class="field full"><label>Demand evidence strength: <b id="demandScoreOut">65</b>/100</label><div class="rangeRow"><input id="demandScore" type="range" min="0" max="100" value="65"><input id="demandScoreNum" type="number" min="0" max="100" value="65"></div></div><div class="field full"><label>Competition intensity: <b id="competitionScoreOut">50</b>/100</label><div class="rangeRow"><input id="competitionScore" type="range" min="0" max="100" value="50"><input id="competitionScoreNum" type="number" min="0" max="100" value="50"></div></div><div class="field full"><label>Supplier confidence: <b id="supplierConfidenceOut">65</b>/100</label><div class="rangeRow"><input id="supplierConfidence" type="range" min="0" max="100" value="65"><input id="supplierConfidenceNum" type="number" min="0" max="100" value="65"></div></div><div class="field full"><label for="evidenceCount">Independent demand signals recorded</label><input id="evidenceCount" type="number" min="0" max="10" step="1" value="1"></div></div></section>
      <main><section id="decision" class="decision validate"><div class="eyebrow">Decision</div><h2 id="verdict">VALIDATE</h2><p id="verdictCopy" class="muted"></p><div class="metric"><span>Opportunity score</span><b id="score">—</b></div><div class="scorebar"><i id="scoreFill"></i></div></section><section class="card"><div class="eyebrow">Economics</div><div class="results"><div class="result"><small>Net profit</small><strong id="profit">—</strong></div><div class="result"><small>Net margin</small><strong id="margin">—</strong></div><div class="result"><small>ROI on landed cost</small><strong id="roi">—</strong></div><div class="result"><small>Break-even price</small><strong id="breakEven">—</strong></div><div class="result"><small>Max landed cost</small><strong id="maxLanded">—</strong></div><div class="result"><small>Max source cost</small><strong id="maxSource">—</strong></div></div><h3>Downside stress tests</h3><table class="scenarioTable"><thead><tr><th>Scenario</th><th>Profit</th><th>Margin</th><th>Verdict</th></tr></thead><tbody id="scenarios"></tbody></table><div class="listblock"><h3>Why this verdict</h3><ul id="reasons"></ul></div><div class="listblock"><h3>Red flags</h3><ul id="risks"></ul></div><div class="listblock"><h3>Validation plan</h3><ul id="plan"></ul></div><div class="toolbar"><button class="btn primary smallbtn" id="savePassport">Save in browser</button><button class="btn smallbtn" id="downloadJson">Download JSON</button><button class="btn smallbtn" id="downloadCsv">Download CSV</button><button class="btn smallbtn" id="printPassport">Print / PDF</button></div><div id="saveNotice" class="legal"></div></section><section class="card savedSection" style="margin-top:20px"><div class="eyebrow">Local decision log</div><h2>Saved passports</h2><p class="muted">Stored only in this browser. Export important records before clearing browser data.</p><div id="saved" class="saved"></div></section></main></div><footer class="footer"><p class="legal">Informational decision support only. Always verify current costs, taxes, marketplace rules, product rights, supplier terms and real demand before committing capital. Support: <a href="mailto:${escapeHtml(supportEmail)}">${escapeHtml(supportEmail)}</a>.</p></footer></div>`, script(), { path: '/dashboard', noindex: true });
  }
  return { dashboard };
}

module.exports = { createDashboardPage };
